### PR TITLE
Bugbash bug fixes

### LINKED ISSUE #27: Sign out of Azure, Try sign in and cancel. Configure Pipelines command is unresponsive

### PR DESCRIPTION
**Pull request by dikhakha**
#27  
#23

### CODE REVIEW

**Review by bishal-pdMSFT — APPROVED** [review]

File: src/configure/helper/devOps/azureDevOpsHelper.ts [hunk 1]
```diff
@@ -25,21 +29,31 @@ export class AzureDevOpsHelper {
         if (remoteUrl.indexOf(AzureDevOpsHelper.AzureReposUrl) >= 0) {
             let part = remoteUrl.substr(remoteUrl.indexOf(AzureDevOpsHelper.AzureReposUrl) + AzureDevOpsHelper.AzureReposUrl.length);
             let parts = part.split('/');
+            if(parts.length !== 4) {
```
Comment (hiyadav) [inline src/configure/helper/devOps/azureDevOpsHelper.ts:32]: this would fail in the case when there is trailing / in the remote url.

Comment (hiyadav) [reply src/configure/helper/devOps/azureDevOpsHelper.ts:32]: Okay, I'll handle at the base layer then
